// <auto-generated />
namespace cv2job.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Feeds1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feeds1));
        
        string IMigrationMetadata.Id
        {
            get { return "201306021709575_Feeds1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
