// <auto-generated />
namespace cv2job.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class utilizadorSobre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(utilizadorSobre));
        
        string IMigrationMetadata.Id
        {
            get { return "201306060457404_utilizadorSobre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
